CREATE TABLE USER (
    USER_ID VARCHAR(36) PRIMARY KEY,
    PASSWORD VARCHAR(500) NOT NULL,
    FULL_NAME VARCHAR(200) NOT NULL,
    OTHER_NAME VARCHAR(200),
    IDNO VARCHAR(30) NOT NULL,
    JOINED_DATE DATE NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PERMANENT TINYINT NOT NULL,
    REMARKS VARCHAR(500),
    FIRST_TIME_LOGIN TINYINT NOT NULL,
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_ON DATETIME NOT NULL,
    MODIFIED_BY VARCHAR(100),
    MODIFIED_ON DATETIME
);

CREATE TABLE PHONE_NO (
    ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) NOT NULL,
    PHONE_NO VARCHAR(50) NOT NULL,
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_ON DATETIME NOT NULL,
    MODIFIED_BY VARCHAR(100),
    MODIFIED_ON DATETIME,
    CONSTRAINT fk_user_phone FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE ADDRESS (
    ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) NOT NULL,
    LINE1 VARCHAR(500) NOT NULL,
    LINE2 VARCHAR(500),
    LINE3 VARCHAR(500),
    LINE4 VARCHAR(500),
    POSTCODE VARCHAR(10) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    STATE VARCHAR(100) NOT NULL,
    NATION VARCHAR(100) NOT NULL,
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_ON DATETIME NOT NULL,
    MODIFIED_BY VARCHAR(100),
    MODIFIED_ON DATETIME,
    CONSTRAINT fk_user_address FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);

