CREATE TABLE TOKENS (
    ID VARCHAR(36) PRIMARY KEY,
    TOKEN VARCHAR(500) NOT NULL,
    USER_ID VARCHAR(36) NOT NULL,
    EXPIRED_AT DATETIME,
    REVOKED TINYINT NOT NULL,
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_ON DATETIME NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    CONSTRAINT unique_token UNIQUE (TOKEN)
);
